# Generated by Django 3.0.6 on 2020-05-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0002_odpowiedzi'),
    ]

    operations = [
        migrations.AddField(
            model_name='odpowiedzi',
            name='prawda',
            field=models.BooleanField(default=False),
        ),
    ]
