# Generated by Django 3.0.6 on 2020-05-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0003_odpowiedzi_prawda'),
    ]

    operations = [
        migrations.CreateModel(
            name='WyborOdpowiedzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Odpowiedz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.Odpowiedzi')),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.Pytania')),
            ],
        ),
    ]
