# Generated by Django 3.0.6 on 2020-05-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0004_wyborodpowiedzi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wyniki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wynik', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
