# Generated by Django 3.0.6 on 2020-05-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0005_uzytkownicy_wyniki'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wyborodpowiedzi',
            old_name='Odpowiedz',
            new_name='odpowiedz',
        ),
    ]
