# Generated by Django 3.0.6 on 2020-05-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0007_auto_20200511_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='pytania',
            name='odp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizy.Odpowiedzi'),
        ),
    ]
