# Generated by Django 3.0.6 on 2020-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0008_pytania_odp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wyborodpowiedzi',
            old_name='odpowiedz',
            new_name='odpowiedzRelacja',
        ),
        migrations.RenameField(
            model_name='wyborodpowiedzi',
            old_name='pytanie',
            new_name='pytanieRelacja',
        ),
        migrations.AddField(
            model_name='wyborodpowiedzi',
            name='Odpowiedz',
            field=models.CharField(default='wpisz odpowiedz', max_length=50),
        ),
    ]
