# Generated by Django 3.0.6 on 2020-05-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0010_auto_20200511_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyborodpowiedzi',
            name='odpowiedzRelacja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizy.Odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='wyborodpowiedzi',
            name='pytanieRelacja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizy.Pytania'),
        ),
    ]
