# Generated by Django 3.0.6 on 2020-05-11 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0011_auto_20200511_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wyborodpowiedzi',
            name='odpowiedzRelacja',
        ),
        migrations.AlterField(
            model_name='wyborodpowiedzi',
            name='pytanieRelacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.Pytania'),
        ),
    ]
