# Generated by Django 3.0.6 on 2020-05-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0013_auto_20200511_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wyborodpowiedzi',
            old_name='pytanieRelacja',
            new_name='pytanie',
        ),
        migrations.RemoveField(
            model_name='pytania',
            name='odp',
        ),
    ]
