# Generated by Django 3.0.6 on 2020-05-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0014_auto_20200511_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyborodpowiedzi',
            name='pytanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.Pytania'),
        ),
    ]
