# Generated by Django 3.0.6 on 2020-05-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0017_uzytkownicy_haslo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyniki',
            name='odpowiedz1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='odpowiedz2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='odpowiedz3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='uzytkownik',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='quizy.Uzytkownicy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wyborodpowiedzi',
            name='pytanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.Pytania'),
        ),
    ]
