# Generated by Django 3.0.6 on 2020-05-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0019_auto_20200513_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyborodpowiedzi',
            name='uzytkownik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizy.Uzytkownicy'),
        ),
        migrations.AlterField(
            model_name='wyborodpowiedzi',
            name='pytanie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizy.Pytania'),
        ),
    ]
