# Generated by Django 3.0.6 on 2020-05-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0022_auto_20200513_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyborodpowiedzi',
            name='uzytkownik',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
