# Generated by Django 3.0.6 on 2020-05-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0023_auto_20200513_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyborodpowiedzi',
            name='uzytkownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizy.Uzytkownicy'),
        ),
    ]
