# Generated by Django 3.0.6 on 2020-05-13 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0024_auto_20200513_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyborodpowiedzi',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizy.Uzytkownicy'),
        ),
    ]
