# Generated by Django 3.0.6 on 2020-05-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0026_auto_20200513_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyniki',
            name='uzytkownik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizy.Uzytkownicy'),
        ),
    ]
