# Generated by Django 3.0.6 on 2020-05-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0027_wyniki_uzytkownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyniki',
            name='wynik',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
