# Generated by Django 3.0.6 on 2020-05-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0028_auto_20200514_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wyniki',
            new_name='WynikiModel',
        ),
    ]
