# Generated by Django 3.0.6 on 2020-05-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizy', '0029_auto_20200514_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pytania',
            name='status',
        ),
    ]
